name: Tests

on: [push, pull_request]

jobs:
  test:

    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies as containers cannot in Github workflows
      run: composer install --no-scripts --no-interaction

    - name: Build container images
      run: make docker_build

    - name: Start containers
      run: make docker_up -- -d

    - name: enable xdebug for coverage
      run: make docker_exec -- phpenmod xdebug

    - name: make tests
      run: make tests -- --coverage-clover=coverage.clover --coverage-text --testdox

    - name: Stop containers
      if: always()
      run: make clean